In [1]:
# Question 1

from array import *
array_num = array('i', [1, 3, 5, 3, 7, 1, 9, 3])
print("Original array: "+str(array_num))

num_list = array_num.tolist()
print("Convert the said array to an ordinary list with the same item:")
print(num_list)

Original array: array('i', [1, 3, 5, 3, 7, 1, 9, 3])
Convert the said array to an ordinary list with the same items:
[1, 3, 5, 3, 7, 1, 9, 3]


In [2]:
from array import *
def array_list(array_num):
    num_list = array_num.tolist() 
    print(num_list)


array_num = array('i', [45,34,67]) 
array_list(array_num)


[45, 34, 67]


In [4]:
# Question 2: first method

import numpy as np
m = np.arange(9).reshape(3,3)
print("Original matrix:")
print(m)
result =  np.trace(m)
print("Condition number of the said matrix:")
print(result)

Original matrix:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Condition number of the said matrix:
12


In [9]:
# Question 2 : second method 
import numpy as np
arr= np.arange(9)
arr= np.reshape(arr,(3,3))
print("Original matrix:")
print(m)

a=np.diagonal(arr, 0,0,1)

result=sum(a)
print("Condition number of the said matrix:")
print(result)

Original matrix:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Condition number of the said matrix:
12


In [20]:
# Question 3

import numpy as np
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(x)
print("Values bigger than 10 =", x[x>10])
print("Their indices are ", np.nonzero(x > 10))


Original array: 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1]), array([2, 0, 1, 2]))


In [10]:
# Question 4
import numpy as np

a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a+b


array([5, 6, 7])

In [12]:
a+5

array([5, 6, 7])

In [11]:
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [14]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [15]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [19]:
# Question 5
import numpy as np
print("Original matrix:\n")
X = np.random.rand(3, 3)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)


Original matrix:

[[0.7653908  0.18499026 0.00320936]
 [0.11597598 0.60843156 0.10051917]
 [0.71891012 0.35771125 0.28894919]]

Subtract the mean of each row of the said matrix:

[[ 0.44752732 -0.13287321 -0.31465411]
 [-0.15899959  0.33345599 -0.1744564 ]
 [ 0.26371993 -0.09747894 -0.16624099]]
